# cloud/nextcloud-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata: { name: nextcloud, namespace: cloud }
spec:
  replicas: 1
  selector: { matchLabels: { app: nextcloud } }
  template:
    metadata: { labels: { app: nextcloud } }
    spec:
      securityContext: { fsGroup: 33 }
      containers:
        - name: nextcloud
          image: nextcloud:29-apache
          env:
            - { name: MYSQL_DATABASE, valueFrom: { secretKeyRef: { name: mariadb-secrets, key: MARIADB_DATABASE } } }
            - { name: MYSQL_USER,     valueFrom: { secretKeyRef: { name: mariadb-secrets, key: MARIADB_USER } } }
            - { name: MYSQL_PASSWORD, valueFrom: { secretKeyRef: { name: mariadb-secrets, key: MARIADB_PASSWORD } } }
            - { name: NEXTCLOUD_ADMIN_USER, valueFrom: { secretKeyRef: { name: nextcloud-admin, key: NEXTCLOUD_ADMIN_USER } } }
            - { name: NEXTCLOUD_ADMIN_PASSWORD, valueFrom: { secretKeyRef: { name: nextcloud-admin, key: NEXTCLOUD_ADMIN_PASSWORD } } }
            - { name: NEXTCLOUD_TRUSTED_DOMAINS, value: "nc.noricam.fr" }
          ports: [{ containerPort: 80, name: http }]
          volumeMounts: [{ name: nc-data, mountPath: /var/www/html }]
      volumes:
        - name: nc-data
          persistentVolumeClaim: { claimName: nextcloud-data }