---
# 1) Namespace où Grafana sera déployé
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---
# 2) Application Argo CD pour Grafana
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 6.43.2
    helm:
      values: |
        ## Désactive la persistance (PVC) si pas de StorageClass
        persistence:
          enabled: false

        ## Active le déploiement de l'Ingress interne
        ingress:
          enabled: true
          ingressClassName: private
          annotations: {}
          # expose sur grafana.nori
          hosts:
            - grafana.nori
          tls: []

        ## On peut baisser les ressources pour un lab
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi

        ## Désactive l'admin / login scopes externes
        adminUser: admin
        adminPassword: "" 

  # Destination = votre cluster TalOS (in-cluster) + namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  # Sync automatique avec prune & self-heal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true